# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='First',
        ),
    ]
